<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use App\Models\User;
use Carbon\Carbon;

class HotelAndPackageSeeder extends Seeder
{
    public function run()
    {
        // Get admin user for relationships
        $admin = User::where('email', 'admin@tourismhub.com')->first();

        if (!$admin) {
            throw new \Exception('Admin user not found. Please run UserSeeder first.');
        }

        $now = Carbon::now();

        // Sample Hotels Data
        $hotels = [
            [
                'user_id' => $admin->id,
                'name' => 'Grand Luxury Resort & Spa',
                'description' => 'Experience unparalleled luxury at our 5-star resort featuring world-class amenities, spa services, and breathtaking ocean views.',
                'address' => '123 Ocean Drive',
                'city' => 'Male',
                'country' => 'Maldives',
                'latitude' => 4.1755,
                'longitude' => 73.5093,
                'phone' => '+960 333-1234',
                'email' => 'info@grandluxury.com',
                'website' => 'https://grandluxury.com',
                'star_rating' => 5,
                'is_featured' => true,
                'is_active' => true,
                'price_per_night' => 15000.00,
                'amenities' => json_encode(['Free WiFi', 'Swimming Pool', 'Spa', 'Fitness Center', 'Restaurant']),
                'images' => json_encode(['https://images.unsplash.com/photo-1571896349842-33c89424de2d']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => $admin->id,
                'name' => 'Mountain View Lodge',
                'description' => 'Nestled in the heart of the Swiss Alps, this cozy lodge offers stunning mountain views and authentic alpine experiences.',
                'address' => 'Alpine Road 45',
                'city' => 'Zermatt',
                'country' => 'Switzerland',
                'latitude' => 46.0207,
                'longitude' => 7.7491,
                'phone' => '+41 27 967 1234',
                'email' => 'info@mountainview.com',
                'website' => 'https://mountainview.com',
                'star_rating' => 4,
                'is_featured' => true,
                'is_active' => true,
                'price_per_night' => 12000.00,
                'amenities' => json_encode(['Hiking Trails', 'Spa', 'Restaurant', 'Free WiFi', 'Fireplace']),
                'images' => json_encode(['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => $admin->id,
                'name' => 'Urban Boutique Hotel',
                'description' => 'A modern boutique hotel in the heart of the city, offering stylish accommodations and easy access to major attractions.',
                'address' => '456 5th Avenue',
                'city' => 'New York',
                'country' => 'USA',
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'phone' => '+1 212-555-1234',
                'email' => 'info@urbanboutique.com',
                'website' => 'https://urbanboutique.com',
                'star_rating' => 4,
                'is_featured' => false,
                'is_active' => true,
                'price_per_night' => 8000.00,
                'amenities' => json_encode(['Free WiFi', 'Restaurant', 'Bar', 'Business Center']),
                'images' => json_encode(['https://images.unsplash.com/photo-1566073771259-6a8506099945']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => $admin->id,
                'name' => 'Desert Oasis Resort',
                'description' => 'Escape to this luxurious desert resort featuring private pools, spa treatments, and authentic Middle Eastern cuisine.',
                'address' => 'Dubai Desert',
                'city' => 'Dubai',
                'country' => 'United Arab Emirates',
                'latitude' => 25.276987,
                'longitude' => 55.296233,
                'phone' => '+971 4 399 7777',
                'email' => 'info@desertoasis.com',
                'website' => 'https://desertoasis.com',
                'star_rating' => 5,
                'is_featured' => true,
                'is_active' => true,
                'price_per_night' => 18000.00,
                'amenities' => json_encode(['Free WiFi', 'Swimming Pool', 'Spa', 'Fitness Center', 'Restaurant']),
                'images' => json_encode(['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => $admin->id,
                'name' => 'Tropical Paradise Resort',
                'description' => 'A beachfront paradise offering water sports, tropical gardens, and authentic island experiences.',
                'address' => 'Jl. Raya Uluwatu',
                'city' => 'Kuta',
                'country' => 'Indonesia',
                'latitude' => -8.722865,
                'longitude' => 115.114986,
                'phone' => '+62 361 8462888',
                'email' => 'info@tropicalparadise.com',
                'website' => 'https://tropicalparadise.com',
                'star_rating' => 4,
                'is_featured' => true,
                'is_active' => true,
                'price_per_night' => 10000.00,
                'amenities' => json_encode(['Free WiFi', 'Swimming Pool', 'Spa', 'Fitness Center', 'Restaurant']),
                'images' => json_encode(['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => $admin->id,
                'name' => 'Historic Castle Hotel',
                'description' => 'Stay in a beautifully restored medieval castle featuring period furnishings and modern amenities.',
                'address' => 'Castle Hill',
                'city' => 'Edinburgh',
                'country' => 'Scotland',
                'latitude' => 55.9552,
                'longitude' => -3.1883,
                'phone' => '+44 131 225 5000',
                'email' => 'info@historiccastle.com',
                'website' => 'https://historiccastle.com',
                'star_rating' => 4,
                'is_featured' => true,
                'is_active' => true,
                'price_per_night' => 9000.00,
                'amenities' => json_encode(['Free WiFi', 'Spa', 'Restaurant', 'Business Center']),
                'images' => json_encode(['https://images.unsplash.com/photo-1542314831-068cd1dbfeeb']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => $admin->id,
                'name' => 'Ski Resort & Spa',
                'description' => 'World-class skiing facilities combined with luxury accommodations and spa services.',
                'address' => 'Aspen Mountain',
                'city' => 'Aspen',
                'country' => 'USA',
                'latitude' => 39.1911,
                'longitude' => -106.8175,
                'phone' => '+1 970 925 8000',
                'email' => 'info@skiresort.com',
                'website' => 'https://skiresort.com',
                'star_rating' => 5,
                'is_featured' => true,
                'is_active' => true,
                'price_per_night' => 14000.00,
                'amenities' => json_encode(['Free WiFi', 'Spa', 'Restaurant', 'Fitness Center', 'Ski Rentals']),
                'images' => json_encode(['https://images.unsplash.com/photo-1511886929837-354984b7fce0']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => $admin->id,
                'name' => 'Vineyard Estate',
                'description' => 'Experience wine country living in this elegant estate surrounded by vineyards and rolling hills.',
                'address' => '123 Vineyard Lane',
                'city' => 'Tuscany',
                'country' => 'Italy',
                'latitude' => 43.5443,
                'longitude' => 11.1589,
                'phone' => '+39 055 802 1234',
                'email' => 'info@vineyardestate.com',
                'website' => 'https://vineyardestate.com',
                'star_rating' => 4,
                'is_featured' => true,
                'is_active' => true,
                'price_per_night' => 11000.00,
                'amenities' => json_encode(['Free WiFi', 'Swimming Pool', 'Spa', 'Fitness Center', 'Restaurant']),
                'images' => json_encode(['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => $admin->id,
                'name' => 'Treehouse Retreat',
                'description' => 'Unique treehouse accommodations in a lush rainforest setting, perfect for nature lovers.',
                'address' => 'Rainforest Trail',
                'city' => 'Costa Rica',
                'country' => 'Costa Rica',
                'latitude' => 10.2464,
                'longitude' => -84.2434,
                'phone' => '+506 2693 1234',
                'email' => 'info@treehouseretreat.com',
                'website' => 'https://treehouseretreat.com',
                'star_rating' => 3,
                'is_featured' => false,
                'is_active' => true,
                'price_per_night' => 6000.00,
                'amenities' => json_encode(['Free WiFi', 'Swimming Pool', 'Spa', 'Fitness Center', 'Restaurant']),
                'images' => json_encode(['https://images.unsplash.com/photo-1518780664697-55e3ad937233']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Sample Tour Packages Data
        $packages = [
            [
                'name' => 'European Grand Tour',
                'description' => 'Explore the best of Europe with this comprehensive tour covering major cities and cultural landmarks.',
                'destination' => 'Europe',
                'duration' => 14,
                'price' => 2500.00,
                'max_participants' => 20,
                'start_time' => '09:00',
                'itinerary' => json_encode([
                    'Day 1: Paris - Eiffel Tower and Seine River Cruise',
                    'Day 2: Paris - Louvre Museum and Notre-Dame',
                    'Day 3: Travel to Rome',
                ]),
                'inclusions' => json_encode([
                    'Hotel accommodations',
                    'Breakfast daily',
                    'Guided tours',
                    'Transportation',
                ]),
                'images' => json_encode(['https://images.unsplash.com/photo-1499856871958-5b9627545d1a']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Safari Adventure',
                'description' => 'Experience the thrill of African wildlife with guided safari tours and luxury accommodations.',
                'destination' => 'Tanzania',
                'duration' => 7,
                'price' => 1800.00,
                'max_participants' => 12,
                'start_time' => '06:00',
                'itinerary' => json_encode([
                    'Day 1: Arrival and Safari Briefing',
                    'Day 2: Serengeti National Park',
                    'Day 3: Ngorongoro Crater',
                ]),
                'inclusions' => json_encode([
                    'Luxury tented camps',
                    'All meals',
                    'Game drives',
                    'Professional guide',
                ]),
                'images' => json_encode(['https://images.unsplash.com/photo-1516426122078-c23e76319801']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Asian Cultural Journey',
                'description' => 'Immerse yourself in the rich cultures of Asia with visits to temples, markets, and historical sites.',
                'destination' => 'Asia',
                'duration' => 10,
                'price' => 2200.00,
                'max_participants' => 15,
                'start_time' => '08:00',
                'itinerary' => json_encode([
                    'Day 1: Arrival in Tokyo',
                    'Day 2: Kyoto - Fushimi Inari Shrine and Kinkaku-ji',
                    'Day 3: Osaka - Castle and Floating Garden',
                    'Day 4: Kyoto - Nijo Castle and Arashiyama',
                    'Day 5: Tokyo - Meiji Shrine and Harajuku',
                ]),
                'inclusions' => json_encode([
                    'Hotel accommodations',
                    'Breakfast daily',
                    'Guided tours',
                    'Transportation',
                ]),
                'images' => json_encode(['https://images.unsplash.com/photo-1528181304800-259b08848526']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Caribbean Cruise',
                'description' => 'Sail through crystal-clear waters, visit tropical islands, and enjoy onboard entertainment.',
                'destination' => 'Caribbean',
                'duration' => 8,
                'price' => 1500.00,
                'max_participants' => 100,
                'start_time' => '12:00',
                'itinerary' => json_encode([
                    'Day 1: Departure from Miami',
                    'Day 2: Nassau, Bahamas',
                    'Day 3: St. Thomas, USVI',
                    'Day 4: St. Maarten',
                    'Day 5: Arrival in Miami',
                ]),
                'inclusions' => json_encode([
                    'All meals',
                    'Entertainment',
                    'Transportation',
                ]),
                'images' => json_encode(['https://images.unsplash.com/photo-1548574505-5e239809ee19']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Northern Lights Expedition',
                'description' => 'Chase the aurora borealis in this unique Arctic adventure with expert guides.',
                'destination' => 'Arctic',
                'duration' => 5,
                'price' => 1200.00,
                'max_participants' => 10,
                'start_time' => '02:00',
                'itinerary' => json_encode([
                    'Day 1: Departure from Reykjavík',
                    'Day 2: Crossing the Arctic Circle',
                    'Day 3: Aurora Sky Watching',
                    'Day 4: Return to Reykjavík',
                    'Day 5: Arrival in Reykjavík',
                ]),
                'inclusions' => json_encode([
                    'Hotel accommodations',
                    'All meals',
                    'Guided tours',
                    'Transportation',
                ]),
                'images' => json_encode(['https://images.unsplash.com/photo-1483347756197-71ef80a95d73']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Wine Country Tour',
                'description' => 'Visit renowned vineyards, enjoy wine tastings, and learn about winemaking processes.',
                'destination' => 'Tuscany',
                'duration' => 6,
                'price' => 950.00,
                'max_participants' => 10,
                'start_time' => '10:00',
                'itinerary' => json_encode([
                    'Day 1: Arrival in Florence',
                    'Day 2: Chianti Region',
                    'Day 3: Siena',
                    'Day 4: Montalcino',
                    'Day 5: Return to Florence',
                ]),
                'inclusions' => json_encode([
                    'Hotel accommodations',
                    'Breakfast daily',
                    'Guided tours',
                    'Wine tasting',
                ]),
                'images' => json_encode(['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Adventure Sports Package',
                'description' => 'Thrill-seekers paradise with activities like rock climbing, white-water rafting, and zip-lining.',
                'destination' => 'Adventure',
                'duration' => 4,
                'price' => 800.00,
                'max_participants' => 10,
                'start_time' => '09:00',
                'itinerary' => json_encode([
                    'Day 1: Arrival in the Adventure Zone',
                    'Day 2: Rock Climbing',
                    'Day 3: White-Water Rafting',
                    'Day 4: Zip-Lining',
                ]),
                'inclusions' => json_encode([
                    'Hotel accommodations',
                    'All meals',
                    'Guided tours',
                    'Transportation',
                ]),
                'images' => json_encode(['https://images.unsplash.com/photo-1530549387789-4c1017266635']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Insert the data
        DB::table('hotels')->insert($hotels);
        DB::table('packages')->insert($packages);
    }
} 